---
- name: Create a dictionary of tags 
  set_fact:
    tags_dict: "{{ tags_dict|default({}) |  combine(item.1) }}"
  with_indexed_items: "{{ tags }}"
  when: (tags is defined and create is defined)

- name: Create a VPC 
  ec2_vpc_net:
    region: "{{ region }}"
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    state: present
    dns_support: "{{ enable_dns_support | default ('true') }}"
    dns_hostnames: "{{ enable_dns_hostnames | default ('true') }}"
    multi_ok: "{{ vpc_multi_ok | default (omit) }}"
    tenancy: "{{ vpc_tenancy | default (omit) }}"
    tags: 
      "{{ tags_dict | default (omit) }}" 
  when: create is defined
  register: vpc_output

- name: Store fact for further use
  set_fact:
    vpc_output: "{{ vpc_output }}"
  when: create is defined

- name: Create a Internet Gateway 
  ec2_vpc_igw:
    region: "{{ region }}"
    vpc_id: "{{ vpc_output.vpc.id }}"
    state: present
    tags: 
      Name: "{{vpc_name}}-igw"
      VPCname: "{{ vpc_name }}"
  when: create is defined
  register: igw_output

- name: Store fact for further use
  set_fact:
    igw_output: "{{ igw_output }}"
  when: create is defined

# Rollback sequence
- name: Gather facts about VPC before deletion
  ec2_vpc_net_facts:
    region: "{{ region }}"
    filters:
      "tag:Name": "{{ vpc_name }}"
  when: rollback is defined
  register: vpc_facts    

- name: Remove the IGW
  ec2_vpc_igw:
    region: "{{ region }}"
    vpc_id: "{{ vpc_facts.vpcs[0].id }}"
    state: absent
  when: rollback is defined

- name: Remove a VPC 
  ec2_vpc_net:
    region: "{{ region }}"
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    state: absent
  when: rollback is defined

# - name: Display all variables/facts 
#   debug:
#     var: hostvars[inventory_hostname]
